Apdex:
  Metadata:
    AlarmConfig:
      Type: ApdexScore
      Iterator: $.Properties.Metrics
      MetricTemplate:
        - Id: satisfied
          MetricStat:
            Metric:
              Dimensions:
                - Name: ApiName
                  Value: ResourceNameIterator
              MetricName: Latency
              Namespace: AWS/ApiGateway
            Period: 300
            Stat: PR(:200)
          ReturnData: false
        - Id: tolerated
          MetricStat:
            Metric:
              Dimensions:
                - Name: ApiName
                  Value: ResourceNameIterator
              MetricName: Latency
              Namespace: AWS/ApiGateway
            Period: 300
            Stat: PR(201:500)
          ReturnData: false        
        - Id: expression
          Expression: satisfied + (tolerated / 2)
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmDescription: Apdex < 90 for ResourceNameIterator
    ComparisonOperator: LessThanOrEqualToThreshold
    EvaluationPeriods: 1
    Metrics: []
    Threshold: 90
    TreatMissingData: notBreaching
