QueueDepthAlarm:
  Metadata:
    AlarmConfig:
      Type: ListExpression
      Name: QueueDepth
      Path: $.Properties.Metrics
      MetricTemplate:
        - Id: m
          MetricStat:
            Metric:
              Dimensions:
                - Name: QueueName
                  Value: 
                    Fn::GetAtt: [ ResourceNameIterator, QueueName] 
              MetricName: ApproximateNumberOfMessagesVisible
              Namespace: AWS/SQS
            Stat: Sum
            Period: 300
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmDescription: Queue depth > 10 on ResourceNameIterator
    Metrics: []
    EvaluationPeriods: 1
    Threshold: 10
    ComparisonOperator: GreaterThanThreshold
